### ISSUE TITLE
Build Errors on MacOS

### ISSUE THREAD

**Issue by tkellogg** [so-dang-cool/dt#9]
I downloaded and unzipped the 1.0.0 zip file and tried unsuccessfully to build. Am I missing a step?

```
❯ ./build compile
/Users/timkellogg/Downloads/dt-1.0.0/build.zig:5:23: error: no field or member function named 'standardOptimizeOption' in 'build.Builder'
    const optimize = b.standardOptimizeOption(.{});
                     ~^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/zig/0.10.1/lib/zig/std/build.zig:31:21: note: struct declared here
pub const Builder = struct {
                    ^~~~~~
referenced by:
    runBuild: /usr/local/Cellar/zig/0.10.1/lib/zig/build_runner.zig:232:22
    usage__anon_4562: /usr/local/Cellar/zig/0.10.1/lib/zig/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
````

**Comment by booniepepper** [comment]
Thanks for taking a look!

I'll have to add a better warning in the release notes and in the build script itself.

Right now the project will only build with Zig 0.11.0 or higher (currently the "master" release https://ziglang.org/download/). If you also want to run tests, you'll need to have a recent version of cargo, but nothing unstable.

_As a side note: I don't plan to track unstable versions of Zig in the future, it makes packaging more challenging, and I might downgrade because of it depending on when Zig 0.11.0 is released. I switched to the version mostly for build/packaging changes that I ultimately didn't require (or at least not yet)._

**Comment by booniepepper** [comment]
Added a note on Zig 0.11.0 requirement for build-from-sourcers in dt 1.0.0 release notes.

**Comment by booniepepper** [comment]
Added Zig versioning requirements to the `build` script, which should make this less mysterious for the next person.

https://github.com/booniepepper/dt/pull/11

I'll roll it into the next release.

**Comment by tkellogg** [comment]
Hey, sorry for the delay. I did a fresh clone and `zig build dt -Doptimize=ReleaseSmall` as the README now says and it gae me this error. Sorry, I don't know much abou zig, not sure what to do

<img width="757" alt="image" src="https://github.com/booniepepper/dt/assets/437044/e54c9ed0-fa38-4940-920d-46a2badb5ef1">

**Comment by tkellogg** [comment]
Hey, how do I install Zig 0.11.0? It's not on the [official downloads page](https://ziglang.org/download/)

**Comment by booniepepper** [comment]
It's currently the "master" version. They're looking to release soon

**Comment by tkellogg** [comment]
Ah, I figured it out eventually. It builds! On macos I had to run `zig` from my `~/Downloads` directory (for anyone else following). The homebrew version was too old.

Now to figure out how this `dt` thing works!
